# Generated by Django 4.0 on 2021-12-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TTClientApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customers',
            table='Customers',
        ),
    ]
