# Generated by Django 4.0 on 2021-12-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTClientApp', '0002_alter_customers_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='is_admin',
            field=models.BooleanField(db_column='is_admin', default=False),
        ),
        migrations.AddField(
            model_name='customers',
            name='is_staff',
            field=models.BooleanField(db_column='is_staff', default=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, db_column='date_joined'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='last_login',
            field=models.DateTimeField(auto_now=True, db_column='last_login'),
        ),
    ]
