# Generated by Django 3.2.8 on 2022-01-16 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TTClientApp', '0003_customers_is_admin_customers_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': False},
        ),
    ]
